### PR TITLE
Christopher

### PR DESCRIPTION
**Pull request by ChristopherArias-Hash**
This is merging, the main screen (not the camera disregard the commit message) to develop! Please use this as our main app for now on.

### CODE REVIEW

**Comment by IsaaccCSUCI** [comment]
Looks Good!

**Review by IsaaccCSUCI — APPROVED** [review]

**Comment by EthanEvirs** [comment]
Test accept

**Review by EthanEvirs — COMMENTED** [review]
Nice work!

**Comment by EthanEvirs** [comment]
hhh

**Review by EthanEvirs — APPROVED** [review]
hj

**Pull request merged**
